from enum import StrEnum


class SampleState(StrEnum):
    DISCOVERED = "DISCOVERED"
    INITIALIZING = "INITIALIZING"
    INITIALIZED = "INITIALIZED"
    IDA_ANALYSIS = "IDA_ANALYSIS"
    EXTRACTING = "EXTRACTING"
    GRAPH_BUILDING = "GRAPH_BUILDING"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    ANALYZING = "ANALYZING"
    AI_ANALYZED = "AI_ANALYZED"
    INVESTIGATING = "INVESTIGATING"
    MCP_INVESTIGATED = "MCP_INVESTIGATED"
    PROPAGATING = "PROPAGATING"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    ENRICHING = "ENRICHING"
    ENRICHED = "ENRICHED"
    REPORTING = "REPORTING"
    COMPLETE = "COMPLETE"
    FAILED_IDA = "FAILED_IDA"
    FAILED_EXTRACTION = "FAILED_EXTRACTION"
    FAILED_AI = "FAILED_AI"
    FAILED_MCP = "FAILED_MCP"
    FAILED_PROPAGATION = "FAILED_PROPAGATION"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    FAILED_ENRICHMENT = "FAILED_ENRICHMENT"
    FAILED_REPORT = "FAILED_REPORT"


class JobStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
